services:
  fastapi_app:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always

    networks:
      - youtube_network

networks:
  youtube_network:
    driver: bridge
